version: '3'
services:

  dt-roscore:
    image: duckietown/dt-ros-kinetic-base:ente-${ARCH-arm32v7}
    container_name: roscore
    restart: unless-stopped
    network_mode: host
    command: roscore

  dt-duckiebot-interface:
    image: duckietown/dt-duckiebot-interface:ente-${ARCH-arm32v7}
    container_name: duckiebot-interface
    restart: unless-stopped
    network_mode: host
    privileged: true
    volumes:
      - /data:/data
      # avahi services
      - /etc/avahi/services:/etc/avahi/services

  dt-car-interface:
    image: duckietown/dt-car-interface:ente-${ARCH-arm32v7}
    container_name: car-interface
    restart: unless-stopped
    network_mode: host
    privileged: true
    volumes:
      - /data:/data
      # avahi services
      - /etc/avahi/services:/etc/avahi/services

  dt-ros-websocket:
    image: duckietown/dt-rosbridge-websocket:ente-${ARCH-arm32v7}
    container_name: rosbridge-websocket
    restart: unless-stopped
    network_mode: "host"
    volumes:
      # avahi services
      - /etc/avahi/services:/etc/avahi/services

  dt-files-api:
    image: duckietown/dt-files-api:ente-${ARCH-arm32v7}
    container_name: files-api
    restart: unless-stopped
    ports:
      - "8082:8082/tcp"
    volumes:
      - /data:/data
      # avahi services
      - /etc/avahi/services:/etc/avahi/services
    working_dir: /data
