version: '3'
services:

  car-interface:
    image: duckietown/car-interface:master19-${ARCH:-arm32v7}
    restart: unless-stopped
    network_mode: "host"
    environment:
      - VEHICLE_NAME=${VEHICLE_NAME:- }

  supercamera:
    image: duckietown/supercamera:master19-${ARCH:-arm32v7}
    restart: unless-stopped
    network_mode: "host"
    environment:
      - VEHICLE_NAME=${VEHICLE_NAME:- }
